name: Call unit tests workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  call-shared-workflow:
    uses: my-org/shared-workflows/.github/workflows/unit-tests.yml@main
    with:
      node_version: '22'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
