name: Call unit tests workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  call-shared-workflow:
    uses: ckomop0x/shared-workflows/.github/workflows/unit-tests.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
